
version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:stable

commands:
  print_pipline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  save_hello_world_output:
    <<: *defaults
    steps:
      - print_pipline_id
      - run: echo "hello from workspace" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  display-author:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "echo author name"
          command: |
            echo $author_name

workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - display-author
