
version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hello from workspace" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  display-author:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "echo author name"
          command: |
            echo $author_name

workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - display-author
